# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab8Constrian.xdc

# Block Designs: bd/lab8_part1/lab8_part1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1 || ORIG_REF_NAME==lab8_part1}]

# IP: bd/lab8_part1/ip/lab8_part1_processing_system7_0_0/lab8_part1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1_processing_system7_0_0 || ORIG_REF_NAME==lab8_part1_processing_system7_0_0}]

# XDC: bd/lab8_part1/ip/lab8_part1_processing_system7_0_0/lab8_part1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab8_part1_processing_system7_0_0 || ORIG_REF_NAME==lab8_part1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/lab8_part1/lab8_part1_ooc.xdc
