# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/xup/embedded/lab8_part1_zsy/lab8_part1_zsy.cache/wt [current_project]
set_property parent.project_path C:/xup/embedded/lab8_part1_zsy/lab8_part1_zsy.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
add_files C:/xup/embedded/lab8_part1_zsy/lab8_part1_zsy.srcs/sources_1/bd/lab8_part1/lab8_part1.bd
set_property used_in_implementation false [get_files -all c:/xup/embedded/lab8_part1_zsy/lab8_part1_zsy.srcs/sources_1/bd/lab8_part1/ip/lab8_part1_processing_system7_0_0/lab8_part1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/xup/embedded/lab8_part1_zsy/lab8_part1_zsy.srcs/sources_1/bd/lab8_part1/lab8_part1_ooc.xdc]
set_property is_locked true [get_files C:/xup/embedded/lab8_part1_zsy/lab8_part1_zsy.srcs/sources_1/bd/lab8_part1/lab8_part1.bd]

read_verilog -library xil_defaultlib C:/xup/embedded/lab8_part1_zsy/lab8_part1_zsy.srcs/sources_1/bd/lab8_part1/hdl/lab8_part1_wrapper.v
read_xdc C:/xup/embedded/lab8_part1_zsy/lab8_part1_zsy.srcs/constrs_1/new/lab8Constrian.xdc
set_property used_in_implementation false [get_files C:/xup/embedded/lab8_part1_zsy/lab8_part1_zsy.srcs/constrs_1/new/lab8Constrian.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top lab8_part1_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef lab8_part1_wrapper.dcp
catch { report_utilization -file lab8_part1_wrapper_utilization_synth.rpt -pb lab8_part1_wrapper_utilization_synth.pb }
