# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.cache/wt [current_project]
set_property parent.project_path C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/sources_1/imports/lab7ece530winter2017zsy/DelayLoop.v
  C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/sources_1/imports/lab7ece530winter2017zsy/kcuart_rx.v
  C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/sources_1/imports/lab7ece530winter2017zsy/kcuart_tx.v
  C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/sources_1/imports/lab7ece530winter2017zsy/bbfifo_16x8.v
  C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/sources_1/imports/lab7ece530winter2017zsy/DebouncerWithoutLatch.v
  C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/sources_1/imports/lab7ece530winter2017zsy/uart_tx.v
  C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/sources_1/imports/lab7ece530winter2017zsy/BaudRateGenerator.v
  C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/sources_1/imports/lab7ece530winter2017zsy/ClockedOneShot.v
  C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/sources_1/imports/lab7ece530winter2017zsy/uart_rx.v
  C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/sources_1/imports/lab7ece530winter2017zsy/uartTestece530winter2017.v
}
read_xdc C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/constrs_1/new/uartTestece530winter2017.xdc
set_property used_in_implementation false [get_files C:/xup/embedded/lab7ece530winter2017zsy/lab7ece530winter2017zsy.srcs/constrs_1/new/uartTestece530winter2017.xdc]

synth_design -top uartTestece530winter2017 -part xc7z010clg400-1
write_checkpoint -noxdef uartTestece530winter2017.dcp
catch { report_utilization -file uartTestece530winter2017_utilization_synth.rpt -pb uartTestece530winter2017_utilization_synth.pb }
