webtalk_init -webtalk_dir C:\\xup\\embedded\\lab8_part2\\lab8_part2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 10 20:12:22 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cdph6n2sbstr77er79rrmgvqbk" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_18" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1515609472747" -context "sdk\\\\bsp/1515609472747"
webtalk_add_data -client sdk -key hwid -value "1513801977261" -context "sdk\\\\bsp/1515609472747"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1515609472747"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1515609472747"
webtalk_add_data -client sdk -key uid -value "1515609477780" -context "sdk\\\\application/1515609477780"
webtalk_add_data -client sdk -key hwid -value "1513801977261" -context "sdk\\\\application/1515609477780"
webtalk_add_data -client sdk -key bspid -value "1515609472747" -context "sdk\\\\application/1515609477780"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1515609477780"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1515609477780"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1515609477780"
webtalk_add_data -client sdk -key uid -value "1515609716889" -context "sdk\\\\bsp/1515609716889"
webtalk_add_data -client sdk -key hwid -value "1515542658567" -context "sdk\\\\bsp/1515609716889"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1515609716889"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1515609716889"
webtalk_add_data -client sdk -key uid -value "1515609722080" -context "sdk\\\\application/1515609722080"
webtalk_add_data -client sdk -key hwid -value "1515542658567" -context "sdk\\\\application/1515609722080"
webtalk_add_data -client sdk -key bspid -value "1515609716889" -context "sdk\\\\application/1515609722080"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1515609722080"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1515609722080"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1515609722080"
webtalk_transmit -clientid 780760726 -regid "" -xml C:\\xup\\embedded\\lab8_part2\\lab8_part2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\xup\\embedded\\lab8_part2\\lab8_part2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\xup\\embedded\\lab8_part2\\lab8_part2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
