# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.cache/wt [current_project]
set_property parent.project_path C:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths c:/xup/embedded/lab10VGAdemoZSY/lib [current_project]
add_files C:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/lab10VGAdemoZSY.bd
set_property used_in_implementation false [get_files -all c:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_processing_system7_0_0/lab10VGAdemoZSY_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_axi_vdma_0_0/lab10VGAdemoZSY_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_axi_vdma_0_0/lab10VGAdemoZSY_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_axi_vdma_0_0/lab10VGAdemoZSY_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_rst_processing_system7_0_100M_0/lab10VGAdemoZSY_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_rst_processing_system7_0_100M_0/lab10VGAdemoZSY_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_rst_processing_system7_0_100M_0/lab10VGAdemoZSY_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_xbar_1/lab10VGAdemoZSY_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_auto_pc_0/lab10VGAdemoZSY_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_auto_pc_1/lab10VGAdemoZSY_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/lab10VGAdemoZSY_ooc.xdc]
set_property is_locked true [get_files C:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/lab10VGAdemoZSY.bd]

read_verilog -library xil_defaultlib C:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/sources_1/bd/lab10VGAdemoZSY/hdl/lab10VGAdemoZSY_wrapper.v
read_xdc C:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/constrs_1/new/lab10.xdc
set_property used_in_implementation false [get_files C:/xup/embedded/lab10VGAdemoZSY/lab10VGAdemoZSY.srcs/constrs_1/new/lab10.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top lab10VGAdemoZSY_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef lab10VGAdemoZSY_wrapper.dcp
catch { report_utilization -file lab10VGAdemoZSY_wrapper_utilization_synth.rpt -pb lab10VGAdemoZSY_wrapper_utilization_synth.pb }
