# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab10.xdc

# Block Designs: bd/lab10VGAdemoZSY/lab10VGAdemoZSY.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY || ORIG_REF_NAME==lab10VGAdemoZSY}]

# IP: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_processing_system7_0_0/lab10VGAdemoZSY_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_processing_system7_0_0 || ORIG_REF_NAME==lab10VGAdemoZSY_processing_system7_0_0}]

# IP: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_axi_vdma_0_0/lab10VGAdemoZSY_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_axi_vdma_0_0 || ORIG_REF_NAME==lab10VGAdemoZSY_axi_vdma_0_0}]

# IP: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_axi_mem_intercon_0/lab10VGAdemoZSY_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_axi_mem_intercon_0 || ORIG_REF_NAME==lab10VGAdemoZSY_axi_mem_intercon_0}]

# IP: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_rst_processing_system7_0_100M_0/lab10VGAdemoZSY_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab10VGAdemoZSY_rst_processing_system7_0_100M_0}]

# IP: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_processing_system7_0_axi_periph_0/lab10VGAdemoZSY_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==lab10VGAdemoZSY_processing_system7_0_axi_periph_0}]

# IP: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_axi_dispctrl_0_0/lab10VGAdemoZSY_axi_dispctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_axi_dispctrl_0_0 || ORIG_REF_NAME==lab10VGAdemoZSY_axi_dispctrl_0_0}]

# IP: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_xbar_1/lab10VGAdemoZSY_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_xbar_1 || ORIG_REF_NAME==lab10VGAdemoZSY_xbar_1}]

# IP: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_xlconstant_0_0/lab10VGAdemoZSY_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_xlconstant_0_0 || ORIG_REF_NAME==lab10VGAdemoZSY_xlconstant_0_0}]

# IP: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_auto_pc_0/lab10VGAdemoZSY_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_auto_pc_0 || ORIG_REF_NAME==lab10VGAdemoZSY_auto_pc_0}]

# IP: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_auto_pc_1/lab10VGAdemoZSY_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_auto_pc_1 || ORIG_REF_NAME==lab10VGAdemoZSY_auto_pc_1}]

# XDC: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_processing_system7_0_0/lab10VGAdemoZSY_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_processing_system7_0_0 || ORIG_REF_NAME==lab10VGAdemoZSY_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_axi_vdma_0_0/lab10VGAdemoZSY_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_axi_vdma_0_0 || ORIG_REF_NAME==lab10VGAdemoZSY_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_axi_vdma_0_0/lab10VGAdemoZSY_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_axi_vdma_0_0 || ORIG_REF_NAME==lab10VGAdemoZSY_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_axi_vdma_0_0/lab10VGAdemoZSY_axi_vdma_0_0_ooc.xdc

# XDC: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_rst_processing_system7_0_100M_0/lab10VGAdemoZSY_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab10VGAdemoZSY_rst_processing_system7_0_100M_0}]

# XDC: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_rst_processing_system7_0_100M_0/lab10VGAdemoZSY_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab10VGAdemoZSY_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==lab10VGAdemoZSY_rst_processing_system7_0_100M_0}]

# XDC: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_rst_processing_system7_0_100M_0/lab10VGAdemoZSY_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_xbar_1/lab10VGAdemoZSY_xbar_1_ooc.xdc

# XDC: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_auto_pc_0/lab10VGAdemoZSY_auto_pc_0_ooc.xdc

# XDC: bd/lab10VGAdemoZSY/ip/lab10VGAdemoZSY_auto_pc_1/lab10VGAdemoZSY_auto_pc_1_ooc.xdc

# XDC: bd/lab10VGAdemoZSY/lab10VGAdemoZSY_ooc.xdc
