set_property PACKAGE_PIN V20 [get_ports iic_1_scl_io]
set_property PACKAGE_PIN W20 [get_ports iic_1_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_1_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_1_sda_io]

set_property DRIVE 8 [get_ports iic_1_scl_io]
set_property DRIVE 8 [get_ports iic_1_sda_io]

set_property PACKAGE_PIN D18 [get_ports {transmitted_bits_1[3]}]
set_property PACKAGE_PIN G14 [get_ports {transmitted_bits_1[2]}]
set_property PACKAGE_PIN M15 [get_ports {transmitted_bits_1[1]}]
set_property PACKAGE_PIN M14 [get_ports {transmitted_bits_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {transmitted_bits_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {transmitted_bits_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {transmitted_bits_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {transmitted_bits_1[0]}]
set_property PACKAGE_PIN W15 [get_ports rx]
set_property PACKAGE_PIN V15 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
