# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab8Constrian.xdc

# Block Designs: bd/lab8_part1/lab8_part1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1 || ORIG_REF_NAME==lab8_part1}]

# IP: bd/lab8_part1/ip/lab8_part1_processing_system7_0_0/lab8_part1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1_processing_system7_0_0 || ORIG_REF_NAME==lab8_part1_processing_system7_0_0}]

# IP: bd/lab8_part1/ip/lab8_part1_axi_gpio_1_0/lab8_part1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1_axi_gpio_1_0 || ORIG_REF_NAME==lab8_part1_axi_gpio_1_0}]

# IP: bd/lab8_part1/ip/lab8_part1_processing_system7_0_axi_periph_3/lab8_part1_processing_system7_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1_processing_system7_0_axi_periph_3 || ORIG_REF_NAME==lab8_part1_processing_system7_0_axi_periph_3}]

# IP: bd/lab8_part1/ip/lab8_part1_rst_processing_system7_0_100M_3/lab8_part1_rst_processing_system7_0_100M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1_rst_processing_system7_0_100M_3 || ORIG_REF_NAME==lab8_part1_rst_processing_system7_0_100M_3}]

# IP: bd/lab8_part1/ip/lab8_part1_xbar_3/lab8_part1_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1_xbar_3 || ORIG_REF_NAME==lab8_part1_xbar_3}]

# IP: bd/lab8_part1/ip/lab8_part1_UARTmodule2017winter_0_1/lab8_part1_UARTmodule2017winter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1_UARTmodule2017winter_0_1 || ORIG_REF_NAME==lab8_part1_UARTmodule2017winter_0_1}]

# IP: bd/lab8_part1/ip/lab8_part1_axi_gpio_0_1/lab8_part1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1_axi_gpio_0_1 || ORIG_REF_NAME==lab8_part1_axi_gpio_0_1}]

# IP: bd/lab8_part1/ip/lab8_part1_auto_pc_0/lab8_part1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1_auto_pc_0 || ORIG_REF_NAME==lab8_part1_auto_pc_0}]

# XDC: bd/lab8_part1/ip/lab8_part1_processing_system7_0_0/lab8_part1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab8_part1_processing_system7_0_0 || ORIG_REF_NAME==lab8_part1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/lab8_part1/ip/lab8_part1_axi_gpio_1_0/lab8_part1_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab8_part1_axi_gpio_1_0 || ORIG_REF_NAME==lab8_part1_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/lab8_part1/ip/lab8_part1_axi_gpio_1_0/lab8_part1_axi_gpio_1_0_ooc.xdc

# XDC: bd/lab8_part1/ip/lab8_part1_axi_gpio_1_0/lab8_part1_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab8_part1_axi_gpio_1_0 || ORIG_REF_NAME==lab8_part1_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/lab8_part1/ip/lab8_part1_rst_processing_system7_0_100M_3/lab8_part1_rst_processing_system7_0_100M_3_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1_rst_processing_system7_0_100M_3 || ORIG_REF_NAME==lab8_part1_rst_processing_system7_0_100M_3}]

# XDC: bd/lab8_part1/ip/lab8_part1_rst_processing_system7_0_100M_3/lab8_part1_rst_processing_system7_0_100M_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab8_part1_rst_processing_system7_0_100M_3 || ORIG_REF_NAME==lab8_part1_rst_processing_system7_0_100M_3}]

# XDC: bd/lab8_part1/ip/lab8_part1_rst_processing_system7_0_100M_3/lab8_part1_rst_processing_system7_0_100M_3_ooc.xdc

# XDC: bd/lab8_part1/ip/lab8_part1_xbar_3/lab8_part1_xbar_3_ooc.xdc

# XDC: bd/lab8_part1/ip/lab8_part1_axi_gpio_0_1/lab8_part1_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab8_part1_axi_gpio_0_1 || ORIG_REF_NAME==lab8_part1_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/lab8_part1/ip/lab8_part1_axi_gpio_0_1/lab8_part1_axi_gpio_0_1_ooc.xdc

# XDC: bd/lab8_part1/ip/lab8_part1_axi_gpio_0_1/lab8_part1_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lab8_part1_axi_gpio_0_1 || ORIG_REF_NAME==lab8_part1_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/lab8_part1/ip/lab8_part1_auto_pc_0/lab8_part1_auto_pc_0_ooc.xdc

# XDC: bd/lab8_part1/lab8_part1_ooc.xdc
