webtalk_init -webtalk_dir C:\\xup\\embedded\\lab10VGApart2\\lab10VGApart2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jan 23 13:38:25 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "pe27rgcqhigrk98kfv68l64kd7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_25" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "25" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1516729993309" -context "sdk\\\\application/1516729993309"
webtalk_add_data -client sdk -key hwid -value "1516234343846" -context "sdk\\\\application/1516729993309"
webtalk_add_data -client sdk -key bspid -value "1516234449862" -context "sdk\\\\application/1516729993309"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1516729993309"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1516729993309"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1516729993309"
webtalk_add_data -client sdk -key uid -value "1516730990084" -context "sdk\\\\application/1516730990084"
webtalk_add_data -client sdk -key hwid -value "1516234343846" -context "sdk\\\\application/1516730990084"
webtalk_add_data -client sdk -key bspid -value "1516234449862" -context "sdk\\\\application/1516730990084"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1516730990084"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1516730990084"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1516730990084"
webtalk_transmit -clientid 2844766567 -regid "" -xml C:\\xup\\embedded\\lab10VGApart2\\lab10VGApart2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\xup\\embedded\\lab10VGApart2\\lab10VGApart2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\xup\\embedded\\lab10VGApart2\\lab10VGApart2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
